slogo_team07: parser.Node Class Reference
parser.Node Class Reference
Public Member Functions
Node (String value, Node child1, Node child2)
String getValue ()
void addChild (Node newNode)
int numChildren ()
boolean hasChildren ()
Node getChild1 ()
Node getChild2 ()
boolean isLeaf ()
void insertChild (Node newNode, String command)
Private Attributes
String myValue
Node myChild1
Node myChild2
Detailed Description
The Node class is for creating trees
Author
Megan
Definition at line 9 of file Node.java.
Constructor & Destructor Documentation
parser.Node.Node (String value, Node child1, Node child2)
Definition at line 14 of file Node.java.
Member Function Documentation
void parser.Node.addChild (Node newNode)
Definition at line 25 of file Node.java.
Node parser.Node.getChild1 ()
Definition at line 48 of file Node.java.
References parser.Node.myChild1.
Referenced by parser.Parser.generateCommandInput(), parser.Parser.getNodeBeforeToReplace(), and parser.Parser.getNodeForCommand().
Node parser.Node.getChild2 ()
Definition at line 52 of file Node.java.
References parser.Node.myChild2.
Referenced by parser.Parser.generateCommandInput(), parser.Parser.getNodeBeforeToReplace(), and parser.Parser.getNodeForCommand().
String parser.Node.getValue ()
Definition at line 21 of file Node.java.
References parser.Node.myValue.
Referenced by parser.Parser.generateCommandInput(), parser.Parser.getNodeBeforeToReplace(), parser.Node.insertChild(), and parser.Parser.parse().
boolean parser.Node.hasChildren ()
Definition at line 44 of file Node.java.
Referenced by parser.Parser.getNodeBeforeToReplace(), and parser.Parser.getNodeForCommand().
void parser.Node.insertChild (Node newNode, String command)
Definition at line 60 of file Node.java.
References parser.Node.getValue().
Referenced by parser.Parser.parse().
boolean parser.Node.isLeaf ()
Definition at line 56 of file Node.java.
Referenced by parser.Parser.getNodeBeforeToReplace(), and parser.Parser.getNodeForCommand().
int parser.Node.numChildren ()
Definition at line 35 of file Node.java.
Referenced by parser.Parser.generateCommandInput().
Member Data Documentation
Node parser.Node.myChild1 private
Definition at line 11 of file Node.java.
Referenced by parser.Node.getChild1().
Node parser.Node.myChild2 private
Definition at line 12 of file Node.java.
Referenced by parser.Node.getChild2().
String parser.Node.myValue private
Definition at line 10 of file Node.java.
Referenced by parser.Node.getValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/parser/Node.java