slogo_team07: command.AskCommand Class Reference
command.AskCommand Class Reference
Public Member Functions
AskCommand (List< String > params, Map< String, Double > variableMap, Map< String, String > func, List< ObjectProperty > bind, ObservableList< Color > colors)
double run (Turtle t)
Public Member Functions inherited from command.LoopCommand
LoopCommand (List< String > params, Map< String, Double > variableMap, Map< String, String > func, List< ObjectProperty > bind, ObservableList< Color > colors)
Public Member Functions inherited from command.Command
Command (List< String > params, Map< String, Double > variableMap, Map< String, String > func, List< ObjectProperty > bind, ObservableList< Color > color)
void updateVariable (String varName, double val)
abstract double run (Turtle t)
boolean isLoop ()
Map< String, String > getCommandValues (Map< Integer, Turtle > turtles)
Map< String, Double > updateVariables ()
Map< String, String > updateFunctions ()
Protected Member Functions
void updateMap ()
ArrayList< Double > createParameters ()
String makeString (Map< Integer, Turtle > turtles)
Protected Member Functions inherited from command.LoopCommand
List< Double > createParameters ()
void updateMap ()
void addInfo (String s, int i)
Protected Member Functions inherited from command.Command
List< Double > makeParameters ()
Double addParam (String s)
double readVariable (String s)
void createCommandValues ()
String makeString (Map< Integer, Turtle > turtles)
Private Member Functions
List< Integer > makeIDs ()
Additional Inherited Members
Protected Attributes inherited from command.LoopCommand
double start
double end
double incr
String variable
String[] loopInfo
Protected Attributes inherited from command.Command
List< String > strParameters
List< Double > parameters
Map< String, Double > variables
Map< String, String > functions
List< ObjectProperty > bindings
ObservableList< Color > colors
boolean loop
Map< String, String > commandValues
ResourceBundle syntax
Detailed Description
Definition at line 11 of file AskCommand.java.
Constructor & Destructor Documentation
command.AskCommand.AskCommand (List< String > params, Map< String, Double > variableMap, Map< String, String > func, List< ObjectProperty > bind, ObservableList< Color > colors)
Definition at line 13 of file AskCommand.java.
Member Function Documentation
ArrayList<Double> command.AskCommand.createParameters () protected
Definition at line 30 of file AskCommand.java.
List<Integer> command.AskCommand.makeIDs () private
Definition at line 44 of file AskCommand.java.
References command.Command.strParameters.
Referenced by command.AskCommand.makeString().
String command.AskCommand.makeString (Map< Integer, Turtle > turtles) protected
Definition at line 34 of file AskCommand.java.
References command.AskCommand.makeIDs().
double command.AskCommand.run (Turtle t)
Definition at line 18 of file AskCommand.java.
References turtle.Turtle.getID(), command.Command.parameters, and turtle.Turtle.setActive().
void command.AskCommand.updateMap () protected
Definition at line 27 of file AskCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/command/AskCommand.java