slogo_team07: command.CommandFactory Class Reference
command.CommandFactory Class Reference
Public Member Functions
CommandFactory (String l)
Command createCommand (List< String > parts)
int getNumParameters (String s)
void setLanguage (String l)
void updateVariable (String varName, double val)
void initializeLoopVariables (String info)
void clearRepCount ()
void resetRepcount ()
Private Member Functions
void setTranslationMap ()
void checkMake (String cmd, List< String > parts)
Command reflectCMD (String cmd, List< String > parts)
String translateCommand (String s)
Command addVariable (String s, String d)
List< Double > makeParams (List< String > parts)
Double addParam (String s)
boolean isVariable (String s)
double readVariable (String s)
void checkRepeat (String[] parts)
void checkDotimes (String[] parts)
void checkFor (String[] parts)
Private Attributes
Map< String, Double > variables
String language
ResourceBundle translationMap
ResourceBundle paramMap
ResourceBundle syntax
Static Private Attributes
static final int REPEAT = 1
static final int DOTIMES = 2
static final int FOR = 4
static final double DEFAULT_START = 1
Detailed Description
Definition at line 12 of file CommandFactory.java.
Constructor & Destructor Documentation
command.CommandFactory.CommandFactory (String l)
Definition at line 26 of file CommandFactory.java.
References command.CommandFactory.setTranslationMap().
Member Function Documentation
Double command.CommandFactory.addParam (String s) private
Definition at line 118 of file CommandFactory.java.
References command.CommandFactory.isVariable(), and command.CommandFactory.readVariable().
Referenced by command.CommandFactory.makeParams().
Command command.CommandFactory.addVariable (String s, String d) private
Definition at line 99 of file CommandFactory.java.
Referenced by command.CommandFactory.checkMake().
void command.CommandFactory.checkDotimes (String[] parts) private
Definition at line 162 of file CommandFactory.java.
Referenced by command.CommandFactory.initializeLoopVariables().
void command.CommandFactory.checkFor (String[] parts) private
Definition at line 171 of file CommandFactory.java.
Referenced by command.CommandFactory.initializeLoopVariables().
void command.CommandFactory.checkMake (String cmd, List< String > parts) private
Definition at line 46 of file CommandFactory.java.
References command.CommandFactory.addVariable().
Referenced by command.CommandFactory.createCommand().
void command.CommandFactory.checkRepeat (String[] parts) private
Definition at line 155 of file CommandFactory.java.
Referenced by command.CommandFactory.initializeLoopVariables().
void command.CommandFactory.clearRepCount ()
Definition at line 183 of file CommandFactory.java.
Command command.CommandFactory.createCommand (List< String > parts)
Definition at line 38 of file CommandFactory.java.
References command.CommandFactory.checkMake(), command.CommandFactory.reflectCMD(), and command.CommandFactory.translateCommand().
Referenced by parser.Parser.parse().
int command.CommandFactory.getNumParameters (String s)
Definition at line 90 of file CommandFactory.java.
References command.CommandFactory.translateCommand().
Referenced by parser.Parser.makeTree().
void command.CommandFactory.initializeLoopVariables (String info)
Definition at line 146 of file CommandFactory.java.
References command.CommandFactory.checkDotimes(), command.CommandFactory.checkFor(), and command.CommandFactory.checkRepeat().
Referenced by parser.Parser.makeTree().
boolean command.CommandFactory.isVariable (String s) private
Definition at line 130 of file CommandFactory.java.
Referenced by command.CommandFactory.addParam().
List<Double> command.CommandFactory.makeParams (List< String > parts) private
Definition at line 109 of file CommandFactory.java.
References command.CommandFactory.addParam().
Referenced by command.CommandFactory.reflectCMD().
double command.CommandFactory.readVariable (String s) private
Definition at line 134 of file CommandFactory.java.
Referenced by command.CommandFactory.addParam().
Command command.CommandFactory.reflectCMD (String cmd, List< String > parts) private
Definition at line 52 of file CommandFactory.java.
References command.CommandFactory.makeParams().
Referenced by command.CommandFactory.createCommand().
void command.CommandFactory.resetRepcount ()
Definition at line 187 of file CommandFactory.java.
Referenced by parser.Parser.resetRepcount().
void command.CommandFactory.setLanguage (String l)
Definition at line 94 of file CommandFactory.java.
References command.CommandFactory.setTranslationMap().
Referenced by parser.Parser.setLanguage().
void command.CommandFactory.setTranslationMap () private
Definition at line 34 of file CommandFactory.java.
Referenced by command.CommandFactory.CommandFactory(), and command.CommandFactory.setLanguage().
String command.CommandFactory.translateCommand (String s) private
Definition at line 76 of file CommandFactory.java.
Referenced by command.CommandFactory.createCommand(), and command.CommandFactory.getNumParameters().
void command.CommandFactory.updateVariable (String varName, double val)
Definition at line 142 of file CommandFactory.java.
Referenced by parser.Parser.updateVariable().
Member Data Documentation
final double command.CommandFactory.DEFAULT_START = 1 static private
Definition at line 24 of file CommandFactory.java.
final int command.CommandFactory.DOTIMES = 2 static private
Definition at line 22 of file CommandFactory.java.
final int command.CommandFactory.FOR = 4 static private
Definition at line 23 of file CommandFactory.java.
String command.CommandFactory.language private
Definition at line 15 of file CommandFactory.java.
ResourceBundle command.CommandFactory.paramMap private
Definition at line 18 of file CommandFactory.java.
final int command.CommandFactory.REPEAT = 1 static private
Definition at line 21 of file CommandFactory.java.
ResourceBundle command.CommandFactory.syntax private
Definition at line 19 of file CommandFactory.java.
ResourceBundle command.CommandFactory.translationMap private
Definition at line 17 of file CommandFactory.java.
Map<String, Double> command.CommandFactory.variables private
Definition at line 14 of file CommandFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/command/CommandFactory.java