slogo_team07: userInterface.LeftPanel Class Reference
userInterface.LeftPanel Class Reference
Public Member Functions
LeftPanel ()
VBox getPanel ()
void initialize (ObservableMap< String, String > turtleMap, ObservableMap< String, Double > variableMap)
Static Public Member Functions
static synchronized LeftPanel getInstance ()
Private Member Functions
void createEditableTable ()
void fillTableColumn ()
Private Attributes
VBox myLeftPanel
Map< String, String > myTurtles
Map< String, Double > myVariables
TableView turtleTable
TableView< Map.Entry< String, Double > > variableTable
TableColumn turtles
TableColumn turtleIDs
TableColumn< Map.Entry< String, Double >, String > variables
TableColumn< Map.Entry< String, Double >, Double > values
Static Private Attributes
static LeftPanel instance
Detailed Description
Definition at line 17 of file LeftPanel.java.
Constructor & Destructor Documentation
userInterface.LeftPanel.LeftPanel ()
Definition at line 34 of file LeftPanel.java.
Referenced by userInterface.LeftPanel.getInstance().
Member Function Documentation
void userInterface.LeftPanel.createEditableTable () private
general method to create one editable table
Definition at line 93 of file LeftPanel.java.
void userInterface.LeftPanel.fillTableColumn () private
general method used to fill a column with either the keyset or values of a map
Definition at line 100 of file LeftPanel.java.
static synchronized LeftPanel userInterface.LeftPanel.getInstance () static
implements Singleton model
Returns
LeftPanel instance
Definition at line 43 of file LeftPanel.java.
References userInterface.LeftPanel.instance, and userInterface.LeftPanel.LeftPanel().
Referenced by userInterface.UI.initialize().
VBox userInterface.LeftPanel.getPanel ()
for accessing the panel from the UI
Returns
VBox myLeftPanel
Definition at line 57 of file LeftPanel.java.
References userInterface.LeftPanel.myLeftPanel.
Referenced by userInterface.UI.initialize().
void userInterface.LeftPanel.initialize (ObservableMap< String, String > turtleMap, ObservableMap< String, Double > variableMap)
Uses binding to initialize the tables from the maps given and allows values to be edited directly from the table
Parameters
ObservableMap<String,String> turtleMap
ObservableMap<String,Double> variableMap
Definition at line 68 of file LeftPanel.java.
References userInterface.UI.PANEL_HEIGHT, and userInterface.UI.PANEL_WIDTH.
Member Data Documentation
LeftPanel userInterface.LeftPanel.instance static private
LeftPanel represents the left hand portion of the UI
Definition at line 23 of file LeftPanel.java.
Referenced by userInterface.LeftPanel.getInstance().
VBox userInterface.LeftPanel.myLeftPanel private
Definition at line 24 of file LeftPanel.java.
Referenced by userInterface.LeftPanel.getPanel().
Map<String, String> userInterface.LeftPanel.myTurtles private
Definition at line 25 of file LeftPanel.java.
Map<String, Double> userInterface.LeftPanel.myVariables private
Definition at line 26 of file LeftPanel.java.
TableColumn userInterface.LeftPanel.turtleIDs private
Definition at line 30 of file LeftPanel.java.
TableColumn userInterface.LeftPanel.turtles private
Definition at line 29 of file LeftPanel.java.
TableView userInterface.LeftPanel.turtleTable private
Definition at line 27 of file LeftPanel.java.
TableColumn<Map.Entry<String, Double>, Double> userInterface.LeftPanel.values private
Definition at line 32 of file LeftPanel.java.
TableColumn<Map.Entry<String, Double>, String> userInterface.LeftPanel.variables private
Definition at line 31 of file LeftPanel.java.
TableView<Map.Entry<String, Double> > userInterface.LeftPanel.variableTable private
Definition at line 28 of file LeftPanel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/LeftPanel.java