slogo_team07: turtle.Turtle Class Reference
turtle.Turtle Class Reference
Public Member Functions
Turtle (List< ObjectProperty > bindings, Paint color, int ID)
Turtle (int x, int y, double dir, Image i, Paint color, int ID)
boolean isDrawing ()
void setDrawing (boolean b)
String act (Command c)
void move (double pixels)
void fixPos (double height, double width)
void rotate (double degrees)
void setHeading (double degrees)
double getDirection ()
void moveTo (double x, double y)
void previousDrawLine (GraphicsContext gc, double shiftX, double shiftY)
void animatedMove (GraphicsContext gc, double shiftX, double shiftY)
Point2D findNextPoint (double x0, double y0, double x1, double y1)
void updatePenAttributes (GraphicsContext gc)
Pen getPen ()
boolean atGoal ()
boolean isActive ()
int getID ()
Point2D getCurrent ()
Point2D getGoal ()
Turtle (Image i, Paint color, int ID)
Turtle (int x, int y, Image i, Paint color, int ID)
String truncate (double d)
void drawLine (GraphicsContext gc, double shiftX, double shiftY)
void setActive (boolean b)
Private Member Functions
void initializeTurtleDefaults ()
void setUpBindings (List< ObjectProperty > bindings)
double radians ()
void moveMyself (double x, double y)
Private Attributes
double direction
boolean active
int id
double mySpeed
Pen myPen
Point2D current
Point2D next
Point2D goal
ObjectProperty< Image > myImage
Static Private Attributes
static final int DEFAULT_SIZE = 25
static final double DEFAULT_POS = 0
static final double DEFAULT_SPEED = 10.0
static final boolean DEFAULT_DRAW = true
static final boolean DEFAULT_VISIBLE = true
static final Image DEFAULT_IMAGE = new Image("resources/images/default.jpg")
Detailed Description
Definition at line 16 of file Turtle.java.
Constructor & Destructor Documentation
turtle.Turtle.Turtle (List< ObjectProperty > bindings, Paint color, int ID)
Definition at line 35 of file Turtle.java.
References turtle.Turtle.initializeTurtleDefaults(), and turtle.Turtle.setUpBindings().
turtle.Turtle.Turtle (int x, int y, double dir, Image i, Paint color, int ID)
Definition at line 46 of file Turtle.java.
References turtle.Pen.changePenState().
turtle.Turtle.Turtle (Image i, Paint color, int ID)
Definition at line 220 of file Turtle.java.
References turtle.Pen.changePenState(), and turtle.Turtle.DEFAULT_POS.
turtle.Turtle.Turtle (int x, int y, Image i, Paint color, int ID)
Definition at line 232 of file Turtle.java.
References turtle.Pen.changePenState(), and turtle.Turtle.DEFAULT_POS.
Member Function Documentation
String turtle.Turtle.act (Command c)
Definition at line 90 of file Turtle.java.
References command.Command.run().
void turtle.Turtle.animatedMove (GraphicsContext gc, double shiftX, double shiftY)
Definition at line 152 of file Turtle.java.
References turtle.Turtle.findNextPoint(), turtle.Turtle.goal, turtle.Turtle.moveMyself(), turtle.Turtle.mySpeed, and turtle.Pen.penReady().
Referenced by worldController.WorldController.makeKeyFrame().
boolean turtle.Turtle.atGoal ()
Definition at line 198 of file Turtle.java.
References turtle.Turtle.goal.
Referenced by turtle.Turtle.findNextPoint().
void turtle.Turtle.drawLine (GraphicsContext gc, double shiftX, double shiftY)
Definition at line 250 of file Turtle.java.
References turtle.Pen.getColor(), turtle.Pen.getSize(), and turtle.Pen.penReady().
Point2D turtle.Turtle.findNextPoint (double x0, double y0, double x1, double y1)
Definition at line 177 of file Turtle.java.
References turtle.Turtle.atGoal(), turtle.Turtle.goal, and turtle.Turtle.next.
Referenced by turtle.Turtle.animatedMove(), and worldController.WorldController.makeKeyFrame().
void turtle.Turtle.fixPos (double height, double width)
Definition at line 108 of file Turtle.java.
Point2D turtle.Turtle.getCurrent ()
Definition at line 210 of file Turtle.java.
References turtle.Turtle.current.
Referenced by worldController.WorldController.makeKeyFrame().
double turtle.Turtle.getDirection ()
Definition at line 125 of file Turtle.java.
References turtle.Turtle.direction.
Referenced by command.SetTowardsCommand.run(), command.HeadingCommand.run(), and command.SetHeadingCommand.run().
Point2D turtle.Turtle.getGoal ()
Definition at line 214 of file Turtle.java.
References turtle.Turtle.goal.
Referenced by worldController.WorldController.makeKeyFrame().
int turtle.Turtle.getID ()
Definition at line 206 of file Turtle.java.
References turtle.Turtle.id.
Referenced by command.IDCommand.run(), command.TellCommand.run(), and command.AskCommand.run().
Pen turtle.Turtle.getPen ()
Definition at line 194 of file Turtle.java.
References turtle.Turtle.myPen.
void turtle.Turtle.initializeTurtleDefaults () private
Definition at line 58 of file Turtle.java.
References turtle.Pen.changePenState(), turtle.Turtle.DEFAULT_POS, and turtle.Turtle.DEFAULT_SPEED.
Referenced by turtle.Turtle.Turtle().
boolean turtle.Turtle.isActive ()
Definition at line 202 of file Turtle.java.
References turtle.Turtle.active.
boolean turtle.Turtle.isDrawing ()
Definition at line 82 of file Turtle.java.
References turtle.Pen.penReady().
Referenced by command.IsPenDownCommand.run().
void turtle.Turtle.move (double pixels)
Definition at line 94 of file Turtle.java.
References turtle.Turtle.radians().
Referenced by command.BackwardCommand.run(), and command.ForwardCommand.run().
void turtle.Turtle.moveMyself (double x, double y) private
Definition at line 172 of file Turtle.java.
Referenced by turtle.Turtle.animatedMove().
void turtle.Turtle.moveTo (double x, double y)
Definition at line 129 of file Turtle.java.
Referenced by command.HomeCommand.run(), and command.SetPositionCommand.run().
void turtle.Turtle.previousDrawLine (GraphicsContext gc, double shiftX, double shiftY)
Definition at line 138 of file Turtle.java.
References turtle.Pen.penReady().
Referenced by worldController.WorldController.drawTurtle().
double turtle.Turtle.radians () private
Definition at line 104 of file Turtle.java.
Referenced by turtle.Turtle.move().
void turtle.Turtle.rotate (double degrees)
Definition at line 113 of file Turtle.java.
Referenced by command.LeftCommand.run(), and command.RightCommand.run().
void turtle.Turtle.setActive (boolean b)
Definition at line 266 of file Turtle.java.
Referenced by command.TellCommand.run(), and command.AskCommand.run().
void turtle.Turtle.setDrawing (boolean b)
Definition at line 86 of file Turtle.java.
References turtle.Pen.changePenState().
Referenced by command.PenDownCommand.run(), and command.PenUpCommand.run().
void turtle.Turtle.setHeading (double degrees)
Definition at line 118 of file Turtle.java.
References turtle.Turtle.direction.
Referenced by command.HomeCommand.run(), command.SetTowardsCommand.run(), and command.SetHeadingCommand.run().
void turtle.Turtle.setUpBindings (List< ObjectProperty > bindings) private
Definition at line 73 of file Turtle.java.
References userInterface.UIManager.TURTLE_IMAGE_INDEX.
Referenced by turtle.Turtle.Turtle().
String turtle.Turtle.truncate (double d)
Definition at line 245 of file Turtle.java.
void turtle.Turtle.updatePenAttributes (GraphicsContext gc)
Definition at line 189 of file Turtle.java.
References turtle.Pen.getColor(), and turtle.Pen.getSize().
Referenced by worldController.WorldController.update().
Member Data Documentation
boolean turtle.Turtle.active private
Definition at line 26 of file Turtle.java.
Referenced by turtle.Turtle.isActive().
Point2D turtle.Turtle.current private
Definition at line 30 of file Turtle.java.
Referenced by turtle.Turtle.getCurrent().
final boolean turtle.Turtle.DEFAULT_DRAW = true static private
Definition at line 21 of file Turtle.java.
final Image turtle.Turtle.DEFAULT_IMAGE = new Image("resources/images/default.jpg") static private
Definition at line 23 of file Turtle.java.
final double turtle.Turtle.DEFAULT_POS = 0 static private
Definition at line 19 of file Turtle.java.
Referenced by turtle.Turtle.initializeTurtleDefaults(), and turtle.Turtle.Turtle().
final int turtle.Turtle.DEFAULT_SIZE = 25 static private
Definition at line 18 of file Turtle.java.
final double turtle.Turtle.DEFAULT_SPEED = 10.0 static private
Definition at line 20 of file Turtle.java.
Referenced by turtle.Turtle.initializeTurtleDefaults().
final boolean turtle.Turtle.DEFAULT_VISIBLE = true static private
Definition at line 22 of file Turtle.java.
double turtle.Turtle.direction private
Definition at line 25 of file Turtle.java.
Referenced by turtle.Turtle.getDirection(), and turtle.Turtle.setHeading().
Point2D turtle.Turtle.goal private
Definition at line 32 of file Turtle.java.
Referenced by turtle.Turtle.animatedMove(), turtle.Turtle.atGoal(), turtle.Turtle.findNextPoint(), and turtle.Turtle.getGoal().
int turtle.Turtle.id private
Definition at line 27 of file Turtle.java.
Referenced by turtle.Turtle.getID().
ObjectProperty<Image> turtle.Turtle.myImage private
Definition at line 33 of file Turtle.java.
Pen turtle.Turtle.myPen private
Definition at line 29 of file Turtle.java.
Referenced by turtle.Turtle.getPen().
double turtle.Turtle.mySpeed private
Definition at line 28 of file Turtle.java.
Referenced by turtle.Turtle.animatedMove().
Point2D turtle.Turtle.next private
Definition at line 31 of file Turtle.java.
Referenced by turtle.Turtle.findNextPoint().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/turtle/Turtle.java