slogo_team07: world.World Class Reference
world.World Class Reference abstract
Public Member Functions
World (ObservableMap< String, Double > var, ObservableMap< String, String > savedCommands, List< ObjectProperty > Bindings, ObservableList< Color > color) throws IOException
World (int h, int w, ObservableMap< String, Double > var, ObservableMap< String, String > fun, List< ObjectProperty > Bindings, ObservableList< Color > color) throws IOException
World (int h, int w, Turtle t, String language, ObservableMap< String, Double > var, ObservableMap< String, String > fun, List< ObjectProperty > Bindings, ObservableList< Color > color) throws IOException
abstract void fixPosition ()
String listen (String input)
void setLanguage (String language)
Turtle getTurtle ()
Protected Attributes
int height
int width
Map< Integer, Turtle > myTurtles
ObservableMap< String, Double > variables
ObservableMap< String, String > functions
Turtle activeTurtle
Private Member Functions
String runCommand (Command command, int turtleID)
Private Attributes
Parser myParser
Turtle myTurtle
List< ObjectProperty > bindings
ObservableList< Color > colors
Static Private Attributes
static final int DEFAULT_HEIGHT = 100
static final int DEFAULT_WIDTH = 100
static final Color TURTLE_DEFAULT = Color.BLACK
static final String TRUE = "1"
static final String TURTLES_TO_ACT = "turtlesToAct"
static final String LOOP_VARIABLE = "loopVariable"
static final String LOOP_INCREMENT = "loopIncrement"
static final String LOOP_END = "loopEnd"
static final String LOOP_START = "loopStart"
static final String IF_STATEMENT = "ifStatement"
Detailed Description
Definition at line 24 of file World.java.
Constructor & Destructor Documentation
world.World.World (ObservableMap< String, Double > var, ObservableMap< String, String > savedCommands, List< ObjectProperty > Bindings, ObservableList< Color > color) throws IOException
Definition at line 50 of file World.java.
References world.World.DEFAULT_HEIGHT, and world.World.DEFAULT_WIDTH.
world.World.World (int h, int w, ObservableMap< String, Double > var, ObservableMap< String, String > fun, List< ObjectProperty > Bindings, ObservableList< Color > color) throws IOException
Definition at line 66 of file World.java.
world.World.World (int h, int w, Turtle t, String language, ObservableMap< String, Double > var, ObservableMap< String, String > fun, List< ObjectProperty > Bindings, ObservableList< Color > color) throws IOException
Definition at line 82 of file World.java.
Member Function Documentation
abstract void world.World.fixPosition () abstract
Turtle world.World.getTurtle ()
Returns turtle
Returns
Turtle
Definition at line 210 of file World.java.
References world.World.myTurtle.
Referenced by worldController.WorldController.WorldController().
String world.World.listen (String input)
Parameters
String input
Returns
String param
Definition at line 136 of file World.java.
References command.Command.getCommandValues(), parser.Parser.initializeCommands(), parser.Parser.parse(), parser.Parser.resetRepcount(), world.World.runCommand(), and parser.Parser.updateVariable().
Referenced by worldController.WorldController.update().
String world.World.runCommand (Command command, int turtleID) private
Trys to run command on turtle if it exists, if not creates appropriate turtle and runs command
Parameters
Command command
int turtleID
Returns
String param
Definition at line 185 of file World.java.
Referenced by world.World.listen().
void world.World.setLanguage (String language)
Ability to change language of input
Parameters
language
Definition at line 201 of file World.java.
References parser.Parser.setLanguage().
Member Data Documentation
Turtle world.World.activeTurtle protected
Definition at line 33 of file World.java.
List<ObjectProperty> world.World.bindings private
Definition at line 47 of file World.java.
Referenced by world.BoundedWorld.BoundedWorld(), and world.UnboundedWorld.UnboundedWorld().
ObservableList<Color> world.World.colors private
Definition at line 48 of file World.java.
Referenced by world.BoundedWorld.BoundedWorld(), and world.UnboundedWorld.UnboundedWorld().
final int world.World.DEFAULT_HEIGHT = 100 static private
Definition at line 37 of file World.java.
Referenced by world.World.World().
final int world.World.DEFAULT_WIDTH = 100 static private
Definition at line 38 of file World.java.
Referenced by world.World.World().
ObservableMap<String, String> world.World.functions protected
Definition at line 32 of file World.java.
Referenced by world.BoundedWorld.BoundedWorld(), and world.UnboundedWorld.UnboundedWorld().
int world.World.height protected
Definition at line 26 of file World.java.
Referenced by world.UnboundedWorld.fixPosition().
final String world.World.IF_STATEMENT = "ifStatement" static private
Definition at line 46 of file World.java.
final String world.World.LOOP_END = "loopEnd" static private
Definition at line 44 of file World.java.
final String world.World.LOOP_INCREMENT = "loopIncrement" static private
Definition at line 43 of file World.java.
final String world.World.LOOP_START = "loopStart" static private
Definition at line 45 of file World.java.
final String world.World.LOOP_VARIABLE = "loopVariable" static private
Definition at line 42 of file World.java.
Parser world.World.myParser private
Definition at line 34 of file World.java.
Turtle world.World.myTurtle private
Definition at line 35 of file World.java.
Referenced by world.World.getTurtle().
Map<Integer, Turtle> world.World.myTurtles protected
Definition at line 30 of file World.java.
Referenced by world.UnboundedWorld.fixPosition().
final String world.World.TRUE = "1" static private
Definition at line 40 of file World.java.
final Color world.World.TURTLE_DEFAULT = Color.BLACK static private
Definition at line 39 of file World.java.
final String world.World.TURTLES_TO_ACT = "turtlesToAct" static private
Definition at line 41 of file World.java.
ObservableMap<String, Double> world.World.variables protected
Definition at line 31 of file World.java.
Referenced by world.BoundedWorld.BoundedWorld(), and world.UnboundedWorld.UnboundedWorld().
int world.World.width protected
Definition at line 27 of file World.java.
Referenced by world.UnboundedWorld.fixPosition().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/world/World.java