slogo_team07: userInterface.Sidebar Class Reference
userInterface.Sidebar Class Reference
Public Member Functions
Sidebar ()
VBox getSidebar ()
void add (Node n)
void addResult (String s)
Static Public Attributes
static final int TURTLE_INDEX = 0
static final int EDITS_INDEX = 1
static final int PREVIOUS_INDEX = 2
static final int SAVED_INDEX = 3
Protected Member Functions
void addItem (String s, int index)
Protected Attributes
ArrayList< ComboBox< String > > boxes
Package Attributes
ComboBox< String > edits
ComboBox< String > previous
ComboBox< String > saved
Private Member Functions
void initialize ()
void setUpResults ()
void setUpVariableEditor ()
void setUpComboBox (ComboBox< String > cb, String s)
Private Attributes
VBox mySidebar
ComboBox< String > turtles
ScrollPane myResultBox
Text myResults
Static Private Attributes
static final String[] BOX_LABELS
static final int SPACING = 5
Detailed Description
Definition at line 18 of file Sidebar.java.
Constructor & Destructor Documentation
userInterface.Sidebar.Sidebar ()
Definition at line 35 of file Sidebar.java.
References userInterface.Sidebar.initialize().
Member Function Documentation
void userInterface.Sidebar.add (Node n)
Definition at line 43 of file Sidebar.java.
Referenced by userInterface.UserInterface.makeCreateTurtle(), userInterface.UserInterface.makeRunButton(), userInterface.UserInterface.makeSaveCommand(), and userInterface.UserInterface.makeSwitchTurtle().
void userInterface.Sidebar.addItem (String s, int index) protected
Definition at line 47 of file Sidebar.java.
Referenced by userInterface.UserInterface.setUpResponses().
void userInterface.Sidebar.addResult (String s)
Definition at line 78 of file Sidebar.java.
Referenced by worldController.WorldController.update().
VBox userInterface.Sidebar.getSidebar ()
Definition at line 39 of file Sidebar.java.
References userInterface.Sidebar.mySidebar.
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.Sidebar.initialize () private
Definition at line 51 of file Sidebar.java.
References userInterface.Sidebar.setUpComboBox(), userInterface.Sidebar.setUpResults(), and userInterface.Sidebar.setUpVariableEditor().
Referenced by userInterface.Sidebar.Sidebar().
void userInterface.Sidebar.setUpComboBox (ComboBox< String > cb, String s) private
Definition at line 82 of file Sidebar.java.
References userInterface.UserInterface.BOX_WIDTH.
Referenced by userInterface.Sidebar.initialize().
void userInterface.Sidebar.setUpResults () private
Definition at line 64 of file Sidebar.java.
References userInterface.UserInterface.BOX_WIDTH.
Referenced by userInterface.Sidebar.initialize().
void userInterface.Sidebar.setUpVariableEditor () private
Definition at line 73 of file Sidebar.java.
Referenced by userInterface.Sidebar.initialize().
Member Data Documentation
final String [] userInterface.Sidebar.BOX_LABELS static private
Initial value:
= { "Turtles", "Edit Turtle", "Previous Commands",
                                                "Saved Commands" }
Definition at line 25 of file Sidebar.java.
ArrayList<ComboBox<String> > userInterface.Sidebar.boxes protected
Definition at line 31 of file Sidebar.java.
Referenced by userInterface.UserInterface.setUpResponses().
ComboBox<String> userInterface.Sidebar.edits package
Definition at line 30 of file Sidebar.java.
final int userInterface.Sidebar.EDITS_INDEX = 1 static
Definition at line 21 of file Sidebar.java.
ScrollPane userInterface.Sidebar.myResultBox private
Definition at line 32 of file Sidebar.java.
Text userInterface.Sidebar.myResults private
Definition at line 33 of file Sidebar.java.
VBox userInterface.Sidebar.mySidebar private
Definition at line 29 of file Sidebar.java.
Referenced by userInterface.Sidebar.getSidebar().
ComboBox<String> userInterface.Sidebar.previous package
Definition at line 30 of file Sidebar.java.
final int userInterface.Sidebar.PREVIOUS_INDEX = 2 static
Definition at line 22 of file Sidebar.java.
ComboBox<String> userInterface.Sidebar.saved package
Definition at line 30 of file Sidebar.java.
final int userInterface.Sidebar.SAVED_INDEX = 3 static
Definition at line 23 of file Sidebar.java.
Referenced by userInterface.UserInterface.setUpResponses().
final int userInterface.Sidebar.SPACING = 5 static private
Definition at line 27 of file Sidebar.java.
final int userInterface.Sidebar.TURTLE_INDEX = 0 static
Definition at line 20 of file Sidebar.java.
ComboBox<String> userInterface.Sidebar.turtles private
Definition at line 30 of file Sidebar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/Sidebar.java