slogo_team07: factories.CommandFactory Class Reference
factories.CommandFactory Class Reference
Public Member Functions
CommandFactory (String l)
Command createCommand (List< String > parts)
int getNumParameters (String s)
void setLanguage (String l)
void clearRepCount ()
void updateVariable (String varName, double val)
void initializeLoopVariables (String info)
void resetRepcount ()
Private Member Functions
void makeDefaults ()
void setTranslationMap ()
String translateCommand (String s)
Map< String, Command > makeCommandMap (List< Double > params, List< String > parts)
Map< String, Command > booleanCommands (List< Double > params)
Map< String, Command > mathCommands (List< Double > params)
Map< String, Command > queryCommands (List< Double > params)
Map< String, Command > turtleCommands (List< Double > params)
Map< String, Command > loopCommands (List< String > params)
Map< String, Command > ifCommands (List< Double > params)
Command addVariable (String s, String d)
List< Double > makeParams (List< String > parts)
Double addParam (String s)
boolean isVariable (String s)
double readVariable (String s)
Private Attributes
Map< String, Double > variables
List< Double > falseParams
List< Double > trueParams
List< Double > homeParams
String language
ResourceBundle translationMap
ResourceBundle paramMap
ResourceBundle syntax
Static Private Attributes
static final double TRUE = 1
static final double FALSE = 0
static final double DIMENSIONS = 2
static final int REPEAT = 1
static final int DOTIMES = 2
static final int FOR = 4
static final double DEFAULT_START = 1
Detailed Description
Definition at line 11 of file CommandFactory.java.
Constructor & Destructor Documentation
factories.CommandFactory.CommandFactory (String l)
Definition at line 32 of file CommandFactory.java.
References factories.CommandFactory.makeDefaults(), and factories.CommandFactory.setTranslationMap().
Member Function Documentation
Double factories.CommandFactory.addParam (String s) private
Definition at line 213 of file CommandFactory.java.
References factories.CommandFactory.isVariable(), and factories.CommandFactory.readVariable().
Referenced by factories.CommandFactory.makeParams().
Command factories.CommandFactory.addVariable (String s, String d) private
Definition at line 194 of file CommandFactory.java.
Referenced by factories.CommandFactory.createCommand().
Map<String, Command> factories.CommandFactory.booleanCommands (List< Double > params) private
Definition at line 118 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
void factories.CommandFactory.clearRepCount ()
Definition at line 237 of file CommandFactory.java.
Command factories.CommandFactory.createCommand (List< String > parts)
Definition at line 64 of file CommandFactory.java.
References factories.CommandFactory.addVariable(), factories.CommandFactory.makeCommandMap(), factories.CommandFactory.makeParams(), and factories.CommandFactory.translateCommand().
Referenced by parser.Parser.parse().
int factories.CommandFactory.getNumParameters (String s)
Definition at line 95 of file CommandFactory.java.
References factories.CommandFactory.translateCommand().
Referenced by parser.Parser.makeTree().
Map<String, Command> factories.CommandFactory.ifCommands (List< Double > params) private
Definition at line 186 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
void factories.CommandFactory.initializeLoopVariables (String info)
Definition at line 245 of file CommandFactory.java.
Referenced by parser.Parser.makeTree().
boolean factories.CommandFactory.isVariable (String s) private
Definition at line 225 of file CommandFactory.java.
Referenced by factories.CommandFactory.addParam().
Map<String, Command> factories.CommandFactory.loopCommands (List< String > params) private
Definition at line 178 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
Map<String, Command> factories.CommandFactory.makeCommandMap (List< Double > params, List< String > parts) private
Definition at line 104 of file CommandFactory.java.
References factories.CommandFactory.booleanCommands(), factories.CommandFactory.ifCommands(), factories.CommandFactory.loopCommands(), factories.CommandFactory.mathCommands(), factories.CommandFactory.paramMap, factories.CommandFactory.queryCommands(), and factories.CommandFactory.turtleCommands().
Referenced by factories.CommandFactory.createCommand().
void factories.CommandFactory.makeDefaults () private
Definition at line 46 of file CommandFactory.java.
References factories.CommandFactory.DIMENSIONS, and factories.CommandFactory.resetRepcount().
Referenced by factories.CommandFactory.CommandFactory().
List<Double> factories.CommandFactory.makeParams (List< String > parts) private
Definition at line 204 of file CommandFactory.java.
References factories.CommandFactory.addParam().
Referenced by factories.CommandFactory.createCommand().
Map<String, Command> factories.CommandFactory.mathCommands (List< Double > params) private
Definition at line 130 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
Map<String, Command> factories.CommandFactory.queryCommands (List< Double > params) private
Definition at line 148 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
double factories.CommandFactory.readVariable (String s) private
Definition at line 229 of file CommandFactory.java.
Referenced by factories.CommandFactory.addParam().
void factories.CommandFactory.resetRepcount ()
Definition at line 274 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeDefaults(), and parser.Parser.resetRepcount().
void factories.CommandFactory.setLanguage (String l)
Definition at line 99 of file CommandFactory.java.
References factories.CommandFactory.setTranslationMap().
Referenced by parser.Parser.setLanguage().
void factories.CommandFactory.setTranslationMap () private
Definition at line 60 of file CommandFactory.java.
Referenced by factories.CommandFactory.CommandFactory(), and factories.CommandFactory.setLanguage().
String factories.CommandFactory.translateCommand (String s) private
Definition at line 81 of file CommandFactory.java.
Referenced by factories.CommandFactory.createCommand(), and factories.CommandFactory.getNumParameters().
Map<String, Command> factories.CommandFactory.turtleCommands (List< Double > params) private
Definition at line 159 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
void factories.CommandFactory.updateVariable (String varName, double val)
Definition at line 241 of file CommandFactory.java.
Referenced by parser.Parser.updateVariable().
Member Data Documentation
final double factories.CommandFactory.DEFAULT_START = 1 static private
Definition at line 30 of file CommandFactory.java.
final double factories.CommandFactory.DIMENSIONS = 2 static private
Definition at line 25 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeDefaults().
final int factories.CommandFactory.DOTIMES = 2 static private
Definition at line 28 of file CommandFactory.java.
final double factories.CommandFactory.FALSE = 0 static private
Definition at line 24 of file CommandFactory.java.
List<Double> factories.CommandFactory.falseParams private
Definition at line 14 of file CommandFactory.java.
final int factories.CommandFactory.FOR = 4 static private
Definition at line 29 of file CommandFactory.java.
List<Double> factories.CommandFactory.homeParams private
Definition at line 16 of file CommandFactory.java.
String factories.CommandFactory.language private
Definition at line 17 of file CommandFactory.java.
ResourceBundle factories.CommandFactory.paramMap private
Definition at line 20 of file CommandFactory.java.
Referenced by factories.CommandFactory.makeCommandMap().
final int factories.CommandFactory.REPEAT = 1 static private
Definition at line 27 of file CommandFactory.java.
ResourceBundle factories.CommandFactory.syntax private
Definition at line 21 of file CommandFactory.java.
ResourceBundle factories.CommandFactory.translationMap private
Definition at line 19 of file CommandFactory.java.
final double factories.CommandFactory.TRUE = 1 static private
Definition at line 23 of file CommandFactory.java.
List<Double> factories.CommandFactory.trueParams private
Definition at line 15 of file CommandFactory.java.
Map<String, Double> factories.CommandFactory.variables private
Definition at line 13 of file CommandFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/factories/CommandFactory.java