slogo_team07: worldController.WorldController Class Reference
worldController.WorldController Class Reference
Public Member Functions
WorldController (UI ui) throws IOException
WorldController (UI ui, World w)
WorldController (UI ui, boolean bounded) throws IOException
void update (String command)
void clear ()
World getWorld ()
Package Attributes
World myWorld
Private Member Functions
void makeTimeline (int framerate)
KeyFrame makeKeyFrame (int framerate, double xTarget, double yTarget)
void drawTurtle ()
Private Attributes
UI UI
GraphicsContext myGC
Timeline myAnimation
Turtle myTurtle
Canvas myCanvas
StackPane myPane
double shiftX
double shiftY
Static Private Attributes
static final int PAUSE = 10
Detailed Description
Definition at line 29 of file WorldController.java.
Constructor & Destructor Documentation
worldController.WorldController.WorldController (UI ui) throws IOException
Definition at line 44 of file WorldController.java.
References userInterface.UI.getCanvas(), userInterface.UI.getGraphics(), userInterface.UI.getPane(), world.World.getTurtle(), and worldController.WorldController.makeTimeline().
worldController.WorldController.WorldController (UI ui, World w)
Definition at line 59 of file WorldController.java.
References userInterface.UI.getGraphics(), and world.World.getTurtle().
worldController.WorldController.WorldController (UI ui, boolean bounded) throws IOException
Definition at line 67 of file WorldController.java.
References userInterface.UI.getGraphics(), and world.World.getTurtle().
Member Function Documentation
void worldController.WorldController.clear ()
Definition at line 123 of file WorldController.java.
void worldController.WorldController.drawTurtle () private
Definition at line 119 of file WorldController.java.
References turtle.Turtle.previousDrawLine().
Referenced by worldController.WorldController.update().
World worldController.WorldController.getWorld ()
Definition at line 127 of file WorldController.java.
References worldController.WorldController.myWorld.
KeyFrame worldController.WorldController.makeKeyFrame (int framerate, double xTarget, double yTarget) private
Definition at line 85 of file WorldController.java.
References turtle.Turtle.animatedMove(), turtle.Turtle.findNextPoint(), turtle.Turtle.getCurrent(), and turtle.Turtle.getGoal().
Referenced by worldController.WorldController.makeTimeline().
void worldController.WorldController.makeTimeline (int framerate) private
Definition at line 77 of file WorldController.java.
References worldController.WorldController.makeKeyFrame().
Referenced by worldController.WorldController.WorldController().
void worldController.WorldController.update (String command)
Definition at line 110 of file WorldController.java.
References worldController.WorldController.drawTurtle(), world.World.listen(), and turtle.Turtle.updatePenAttributes().
Referenced by userInterface.UI.runCommand().
Member Data Documentation
Timeline worldController.WorldController.myAnimation private
Definition at line 36 of file WorldController.java.
Canvas worldController.WorldController.myCanvas private
Definition at line 38 of file WorldController.java.
GraphicsContext worldController.WorldController.myGC private
Definition at line 35 of file WorldController.java.
StackPane worldController.WorldController.myPane private
Definition at line 39 of file WorldController.java.
Turtle worldController.WorldController.myTurtle private
Definition at line 37 of file WorldController.java.
World worldController.WorldController.myWorld package
Definition at line 33 of file WorldController.java.
Referenced by worldController.WorldController.getWorld().
final int worldController.WorldController.PAUSE = 10 static private
Definition at line 31 of file WorldController.java.
double worldController.WorldController.shiftX private
Definition at line 40 of file WorldController.java.
double worldController.WorldController.shiftY private
Definition at line 41 of file WorldController.java.
UI worldController.WorldController.UI private
Definition at line 34 of file WorldController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/worldController/WorldController.java