slogo_team07: userInterface.TopMenu Class Reference
userInterface.TopMenu Class Reference
Public Member Functions
TopMenu (EventHandler< ActionEvent > tabHandler, List< ObjectProperty > bindings)
MenuBar getMenuBar ()
Package Attributes
Menu Edit
Menu View
Menu Preferences
Menu Help
ObjectProperty< String > penColor
Private Member Functions
void initialize (EventHandler< ActionEvent > tabHandler, List< ObjectProperty > bindings)
Menu createFileMenu ()
Menu createEditMenu ()
Menu createViewMenu ()
Menu createHelpMenu ()
Menu createPreferencesMenu ()
void displayWebpage ()
void displayColorPicker ()
String extractColor (Color c)
void displayPenEditor ()
void displayImagePicker ()
void displayLanguageSelector ()
Pane createDisplayBox (List< Node > nodes)
void display (Node n)
Private Attributes
MenuBar myMenu
Menu File
ColorPicker myBackgroundColorChoices
ColorPicker myPenColorChoices
EventHandler< ActionEvent > createNewTab
Stage myStage
ObjectProperty< String > canvasColor
ObjectProperty< Double > penSize
ObjectProperty< Image > turtleImage
ObjectProperty< ResourceBundle > language
Static Private Attributes
static final String HEX_PREFIX = "x"
static final int COLOR_SUBSTRING_INDEX = 1
static final String COLOR_PATH = "-fx-background-color: #"
static final String IMAGE_PATH = "resources/images/"
static final String RESOURCE_PATH = "resources/languages/"
static final String HTML_HELP_PAGE = "/html/helpPage.html"
static final int PANE_SPACING = 5
static final int POPUP_WIDTH = 250
static final int POPUP_HEIGHT = 150
static final String[] LANGUAGES
Detailed Description
Definition at line 37 of file TopMenu.java.
Constructor & Destructor Documentation
userInterface.TopMenu.TopMenu (EventHandler< ActionEvent > tabHandler, List< ObjectProperty > bindings)
Definition at line 68 of file TopMenu.java.
References userInterface.TopMenu.initialize().
Member Function Documentation
Pane userInterface.TopMenu.createDisplayBox (List< Node > nodes) private
returns the appropriate display box with all desired nodes added on
Definition at line 261 of file TopMenu.java.
Referenced by userInterface.TopMenu.displayColorPicker(), userInterface.TopMenu.displayLanguageSelector(), and userInterface.TopMenu.displayPenEditor().
Menu userInterface.TopMenu.createEditMenu () private
creates Edit part of the MenuBar
Returns
Menu Edit
Definition at line 129 of file TopMenu.java.
References userInterface.TopMenu.Edit.
Referenced by userInterface.TopMenu.initialize().
Menu userInterface.TopMenu.createFileMenu () private
creates File part of the MenuBar
Returns
Menu File
Definition at line 115 of file TopMenu.java.
References userInterface.TopMenu.File.
Referenced by userInterface.TopMenu.initialize().
Menu userInterface.TopMenu.createHelpMenu () private
creates Help part of the MenuBar
Returns
Menu Help
Definition at line 157 of file TopMenu.java.
References userInterface.TopMenu.displayWebpage(), and userInterface.TopMenu.Help.
Referenced by userInterface.TopMenu.initialize().
Menu userInterface.TopMenu.createPreferencesMenu () private
creates Preferences part of the MenuBar
Returns
Menu Preferences
Definition at line 169 of file TopMenu.java.
References userInterface.TopMenu.displayLanguageSelector(), and userInterface.TopMenu.Preferences.
Referenced by userInterface.TopMenu.initialize().
Menu userInterface.TopMenu.createViewMenu () private
creates View part of the MenuBar
Returns
Menu View
Definition at line 140 of file TopMenu.java.
References userInterface.TopMenu.displayColorPicker(), userInterface.TopMenu.displayImagePicker(), userInterface.TopMenu.displayPenEditor(), and userInterface.TopMenu.View.
Referenced by userInterface.TopMenu.initialize().
void userInterface.TopMenu.display (Node n) private
displays any node passed in on a new, centered stage
Definition at line 272 of file TopMenu.java.
Referenced by userInterface.TopMenu.displayColorPicker(), userInterface.TopMenu.displayLanguageSelector(), userInterface.TopMenu.displayPenEditor(), and userInterface.TopMenu.displayWebpage().
void userInterface.TopMenu.displayColorPicker () private
displays the background color editor
Definition at line 191 of file TopMenu.java.
References userInterface.TopMenu.createDisplayBox(), userInterface.TopMenu.display(), and userInterface.TopMenu.extractColor().
Referenced by userInterface.TopMenu.createViewMenu().
void userInterface.TopMenu.displayImagePicker () private
displays a file chooser that allows user to select desired image for turtle
Definition at line 233 of file TopMenu.java.
Referenced by userInterface.TopMenu.createViewMenu().
void userInterface.TopMenu.displayLanguageSelector () private
displays the language selector for the user to pick which language will be read in by the program
Definition at line 246 of file TopMenu.java.
References userInterface.TopMenu.createDisplayBox(), and userInterface.TopMenu.display().
Referenced by userInterface.TopMenu.createPreferencesMenu().
void userInterface.TopMenu.displayPenEditor () private
displays the pen editor that allows user to edit size, color, and style
Definition at line 212 of file TopMenu.java.
References userInterface.TopMenu.createDisplayBox(), userInterface.TopMenu.display(), and userInterface.TopMenu.extractColor().
Referenced by userInterface.TopMenu.createViewMenu().
void userInterface.TopMenu.displayWebpage () private
displays the HTML web page with instructions on SLogo and additional information about the software
Definition at line 181 of file TopMenu.java.
References userInterface.TopMenu.display().
Referenced by userInterface.TopMenu.createHelpMenu().
String userInterface.TopMenu.extractColor (Color c) private
extract the hex values of the Color's string by substringing everything after the 0x;
Parameters
c
Returns
Definition at line 205 of file TopMenu.java.
References userInterface.TopMenu.COLOR_SUBSTRING_INDEX.
Referenced by userInterface.TopMenu.displayColorPicker(), and userInterface.TopMenu.displayPenEditor().
MenuBar userInterface.TopMenu.getMenuBar ()
used by UIManager to get the MenuBar
Returns
MenuBar myMenu
Definition at line 77 of file TopMenu.java.
References userInterface.TopMenu.myMenu.
Referenced by userInterface.UIManager.initialize().
void userInterface.TopMenu.initialize (EventHandler< ActionEvent > tabHandler, List< ObjectProperty > bindings) private
Initializes the components of the TopMenu. Utilizes binding to ensure dynamic changes to the view aspects or language choice.
Parameters
EventHandler<ActionEvent> tabHandler
List<ObjectProperty> bindings
Definition at line 88 of file TopMenu.java.
References userInterface.UIManager.CANVAS_INDEX, userInterface.TopMenu.createEditMenu(), userInterface.TopMenu.createFileMenu(), userInterface.TopMenu.createHelpMenu(), userInterface.TopMenu.createPreferencesMenu(), userInterface.TopMenu.createViewMenu(), userInterface.UIManager.LANGUAGE_INDEX, userInterface.UIManager.PEN_COLOR_INDEX, userInterface.UIManager.PEN_SIZE_INDEX, and userInterface.UIManager.TURTLE_IMAGE_INDEX.
Referenced by userInterface.TopMenu.TopMenu().
Member Data Documentation
ObjectProperty<String> userInterface.TopMenu.canvasColor private
Definition at line 63 of file TopMenu.java.
final String userInterface.TopMenu.COLOR_PATH = "-fx-background-color: #" static private
Definition at line 46 of file TopMenu.java.
final int userInterface.TopMenu.COLOR_SUBSTRING_INDEX = 1 static private
Definition at line 45 of file TopMenu.java.
Referenced by userInterface.TopMenu.extractColor().
EventHandler<ActionEvent> userInterface.TopMenu.createNewTab private
Definition at line 61 of file TopMenu.java.
Menu userInterface.TopMenu.Edit package
Definition at line 58 of file TopMenu.java.
Referenced by userInterface.TopMenu.createEditMenu().
Menu userInterface.TopMenu.File private
Definition at line 58 of file TopMenu.java.
Referenced by userInterface.TopMenu.createFileMenu().
Menu userInterface.TopMenu.Help package
Definition at line 58 of file TopMenu.java.
Referenced by userInterface.TopMenu.createHelpMenu().
final String userInterface.TopMenu.HEX_PREFIX = "x" static private
TopMenu is the menu bar at the top of the UIManager. Holds options to change components of the view or to even create another tab of SLogo
Definition at line 44 of file TopMenu.java.
final String userInterface.TopMenu.HTML_HELP_PAGE = "/html/helpPage.html" static private
Definition at line 49 of file TopMenu.java.
final String userInterface.TopMenu.IMAGE_PATH = "resources/images/" static private
Definition at line 47 of file TopMenu.java.
ObjectProperty<ResourceBundle> userInterface.TopMenu.language private
Definition at line 66 of file TopMenu.java.
final String [] userInterface.TopMenu.LANGUAGES static private
Initial value:
= { "Chinese", "English", "French", "German",
                                               "Italian", "Japanese", "Korean", "Portuguese",
                                               "Russian", "Spanish" }
Definition at line 53 of file TopMenu.java.
ColorPicker userInterface.TopMenu.myBackgroundColorChoices private
Definition at line 59 of file TopMenu.java.
MenuBar userInterface.TopMenu.myMenu private
Definition at line 57 of file TopMenu.java.
Referenced by userInterface.TopMenu.getMenuBar().
ColorPicker userInterface.TopMenu.myPenColorChoices private
Definition at line 60 of file TopMenu.java.
Stage userInterface.TopMenu.myStage private
Definition at line 62 of file TopMenu.java.
final int userInterface.TopMenu.PANE_SPACING = 5 static private
Definition at line 50 of file TopMenu.java.
ObjectProperty<String> userInterface.TopMenu.penColor package
Definition at line 63 of file TopMenu.java.
ObjectProperty<Double> userInterface.TopMenu.penSize private
Definition at line 64 of file TopMenu.java.
final int userInterface.TopMenu.POPUP_HEIGHT = 150 static private
Definition at line 52 of file TopMenu.java.
final int userInterface.TopMenu.POPUP_WIDTH = 250 static private
Definition at line 51 of file TopMenu.java.
Menu userInterface.TopMenu.Preferences package
Definition at line 58 of file TopMenu.java.
Referenced by userInterface.TopMenu.createPreferencesMenu().
final String userInterface.TopMenu.RESOURCE_PATH = "resources/languages/" static private
Definition at line 48 of file TopMenu.java.
ObjectProperty<Image> userInterface.TopMenu.turtleImage private
Definition at line 65 of file TopMenu.java.
Menu userInterface.TopMenu.View package
Definition at line 58 of file TopMenu.java.
Referenced by userInterface.TopMenu.createViewMenu().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/TopMenu.java