slogo_team07: turtle.Pen Class Reference
turtle.Pen Class Reference
Public Member Functions
Pen (Paint color)
void changePenColor (Paint color)
void changePenSize (double size)
Paint getColor ()
double getSize ()
boolean penReady ()
void changePenState (boolean b)
Private Attributes
Paint myPenColor
double mySize
boolean isDrawing
Static Private Attributes
static final double DEFAULT_PEN_SIZE = 2
Detailed Description
Definition at line 5 of file Pen.java.
Constructor & Destructor Documentation
turtle.Pen.Pen (Paint color)
Definition at line 12 of file Pen.java.
References turtle.Pen.DEFAULT_PEN_SIZE.
Member Function Documentation
void turtle.Pen.changePenColor (Paint color)
Definition at line 19 of file Pen.java.
void turtle.Pen.changePenSize (double size)
Definition at line 23 of file Pen.java.
void turtle.Pen.changePenState (boolean b)
Definition at line 39 of file Pen.java.
Referenced by turtle.Turtle.initializeTurtleDefaults(), turtle.Turtle.setDrawing(), and turtle.Turtle.Turtle().
Paint turtle.Pen.getColor ()
Definition at line 27 of file Pen.java.
References turtle.Pen.myPenColor.
Referenced by turtle.Turtle.drawLine(), and turtle.Turtle.updatePenAttributes().
double turtle.Pen.getSize ()
Definition at line 31 of file Pen.java.
References turtle.Pen.mySize.
Referenced by turtle.Turtle.drawLine(), and turtle.Turtle.updatePenAttributes().
boolean turtle.Pen.penReady ()
Definition at line 35 of file Pen.java.
References turtle.Pen.isDrawing.
Referenced by turtle.Turtle.animatedMove(), turtle.Turtle.drawLine(), turtle.Turtle.isDrawing(), and turtle.Turtle.previousDrawLine().
Member Data Documentation
final double turtle.Pen.DEFAULT_PEN_SIZE = 2 static private
Definition at line 6 of file Pen.java.
Referenced by turtle.Pen.Pen().
boolean turtle.Pen.isDrawing private
Definition at line 10 of file Pen.java.
Referenced by turtle.Pen.penReady().
Paint turtle.Pen.myPenColor private
Definition at line 8 of file Pen.java.
Referenced by turtle.Pen.getColor().
double turtle.Pen.mySize private
Definition at line 9 of file Pen.java.
Referenced by turtle.Pen.getSize().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/turtle/Pen.java