slogo_team07: command.LoopCommand Class Reference
command.LoopCommand Class Reference abstract
Public Member Functions
LoopCommand (List< String > params, Map< String, Double > variableMap, Map< String, String > func)
Public Member Functions inherited from command.Command
Command (List< String > params, Map< String, Double > variableMap, Map< String, String > func)
void updateVariable (String varName, double val)
abstract double run (Turtle t)
boolean isLoop ()
Map< String, String > getCommandValues (Map< Integer, Turtle > turtles)
Map< String, Double > updateVariables ()
Map< String, String > updateFunctions ()
Protected Member Functions
List< Double > createParameters ()
void updateMap ()
void addInfo (String s, int i)
Protected Member Functions inherited from command.Command
List< Double > makeParameters ()
Double addParam (String s)
double readVariable (String s)
void createCommandValues ()
String makeString (Map< Integer, Turtle > turtles)
Protected Attributes
double start
double end
double incr
String variable
List< String > strParameters
String[] loopInfo
Protected Attributes inherited from command.Command
List< String > strParameters
List< Double > parameters
Map< String, Double > variables
Map< String, String > functions
boolean loop
Map< String, String > commandValues
ResourceBundle syntax
Detailed Description
Definition at line 7 of file LoopCommand.java.
Constructor & Destructor Documentation
command.LoopCommand.LoopCommand (List< String > params, Map< String, Double > variableMap, Map< String, String > func)
Definition at line 16 of file LoopCommand.java.
References command.Command.loop, and command.LoopCommand.updateMap().
Member Function Documentation
void command.LoopCommand.addInfo (String s, int i) protected
Definition at line 30 of file LoopCommand.java.
References command.Command.commandValues, command.Command.readVariable(), and command.Command.syntax.
Referenced by command.ForCommand.updateMap(), command.DoTimesCommand.updateMap(), and command.RepeatCommand.updateMap().
List<Double> command.LoopCommand.createParameters () protected
Definition at line 22 of file LoopCommand.java.
void command.LoopCommand.updateMap () protected
Definition at line 26 of file LoopCommand.java.
Referenced by command.LoopCommand.LoopCommand().
Member Data Documentation
double command.LoopCommand.end protected
Definition at line 10 of file LoopCommand.java.
double command.LoopCommand.incr protected
Definition at line 11 of file LoopCommand.java.
String [] command.LoopCommand.loopInfo protected
Definition at line 14 of file LoopCommand.java.
Referenced by command.ForCommand.updateMap(), and command.DoTimesCommand.updateMap().
double command.LoopCommand.start protected
Definition at line 9 of file LoopCommand.java.
List<String> command.LoopCommand.strParameters protected
Definition at line 13 of file LoopCommand.java.
Referenced by command.MakeVariableCommand.createParameters(), command.AskCommand.makeIDs(), command.MakeUserInstructionCommand.MakeUserInstructionCommand(), command.MakeUserInstructionCommand.updateFunctions(), and command.MakeVariableCommand.updateVariables().
String command.LoopCommand.variable protected
Definition at line 12 of file LoopCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/command/LoopCommand.java