slogo_team07: userInterface.UIManager Class Reference
userInterface.UIManager Class Reference
Public Member Functions
UIManager ()
Scene getScene ()
Static Public Attributes
static final int UI_WIDTH = 1000
static final int UI_HEIGHT = 750
static final int CANVAS_INDEX = 0
static final int PEN_COLOR_INDEX = 1
static final int PEN_SIZE_INDEX = 2
static final int TURTLE_IMAGE_INDEX = 3
static final int LANGUAGE_INDEX = 4
Package Attributes
ObjectProperty< String > penColor
Private Member Functions
void initialize ()
void setUpBindings ()
void setUpEventHandlers ()
void addTab ()
Private Attributes
TabPane myTabs
BorderPane myView
Scene myScene
TopMenu myMenu
EventHandler< ActionEvent > createNewTab
List< ObjectProperty > myBindings
ObjectProperty< String > canvasColor
ObjectProperty< Double > penSize
ObjectProperty< Image > turtleImage
ObjectProperty< ResourceBundle > language
Static Private Attributes
static final String TAB_NAME = "SLogo #"
static final String DEFAULT_PACKAGE = "resources/languages/English"
static final String DEFAULT_BACKGROUND_COLOR = "-fx-background-color: white"
static final String DEFAULT_PEN_COLOR = "-fx-background-color: black"
static final double DEFAULT_PEN_SIZE = 3
static final Image DEFAULT_IMAGE = new Image("resources/images/default.jpg")
Detailed Description
Definition at line 21 of file UIManager.java.
Constructor & Destructor Documentation
userInterface.UIManager.UIManager ()
Definition at line 54 of file UIManager.java.
References userInterface.UIManager.initialize().
Member Function Documentation
void userInterface.UIManager.addTab () private
method called when user creates new tab on the GUI
Definition at line 106 of file UIManager.java.
References userInterface.UI.getUI().
Referenced by userInterface.UIManager.initialize(), and userInterface.UIManager.setUpEventHandlers().
Scene userInterface.UIManager.getScene ()
returns the scene to be viewed by main
Returns
Scene myScene
Definition at line 92 of file UIManager.java.
References userInterface.UIManager.myScene.
Referenced by Main.start().
void userInterface.UIManager.initialize () private
initializes the necessary components to create a TabPane with at least one instance of UI
Definition at line 61 of file UIManager.java.
References userInterface.UIManager.addTab(), userInterface.TopMenu.getMenuBar(), userInterface.UIManager.setUpBindings(), and userInterface.UIManager.setUpEventHandlers().
Referenced by userInterface.UIManager.UIManager().
void userInterface.UIManager.setUpBindings () private
sets up the binding properties for canvas color, pen color, pen size, turtle image, and language
Definition at line 76 of file UIManager.java.
References userInterface.UIManager.DEFAULT_BACKGROUND_COLOR, userInterface.UIManager.DEFAULT_IMAGE, userInterface.UIManager.DEFAULT_PEN_COLOR, and userInterface.UIManager.DEFAULT_PEN_SIZE.
Referenced by userInterface.UIManager.initialize().
void userInterface.UIManager.setUpEventHandlers () private
sets up all EventHandlers that can be passed into subclasses of the UI
Definition at line 99 of file UIManager.java.
References userInterface.UIManager.addTab().
Referenced by userInterface.UIManager.initialize().
Member Data Documentation
final int userInterface.UIManager.CANVAS_INDEX = 0 static
Definition at line 30 of file UIManager.java.
Referenced by userInterface.UI.initialize(), and userInterface.TopMenu.initialize().
ObjectProperty<String> userInterface.UIManager.canvasColor private
Definition at line 49 of file UIManager.java.
EventHandler<ActionEvent> userInterface.UIManager.createNewTab private
Definition at line 47 of file UIManager.java.
final String userInterface.UIManager.DEFAULT_BACKGROUND_COLOR = "-fx-background-color: white" static private
Definition at line 38 of file UIManager.java.
Referenced by userInterface.UIManager.setUpBindings().
final Image userInterface.UIManager.DEFAULT_IMAGE = new Image("resources/images/default.jpg") static private
Definition at line 41 of file UIManager.java.
Referenced by userInterface.UIManager.setUpBindings().
final String userInterface.UIManager.DEFAULT_PACKAGE = "resources/languages/English" static private
Definition at line 37 of file UIManager.java.
final String userInterface.UIManager.DEFAULT_PEN_COLOR = "-fx-background-color: black" static private
Definition at line 39 of file UIManager.java.
Referenced by userInterface.UIManager.setUpBindings().
final double userInterface.UIManager.DEFAULT_PEN_SIZE = 3 static private
Definition at line 40 of file UIManager.java.
Referenced by userInterface.UIManager.setUpBindings().
ObjectProperty<ResourceBundle> userInterface.UIManager.language private
Definition at line 52 of file UIManager.java.
final int userInterface.UIManager.LANGUAGE_INDEX = 4 static
Definition at line 34 of file UIManager.java.
Referenced by userInterface.UI.initialize(), and userInterface.TopMenu.initialize().
List<ObjectProperty> userInterface.UIManager.myBindings private
Definition at line 48 of file UIManager.java.
TopMenu userInterface.UIManager.myMenu private
Definition at line 46 of file UIManager.java.
Scene userInterface.UIManager.myScene private
Definition at line 45 of file UIManager.java.
Referenced by userInterface.UIManager.getScene().
TabPane userInterface.UIManager.myTabs private
Definition at line 43 of file UIManager.java.
BorderPane userInterface.UIManager.myView private
Definition at line 44 of file UIManager.java.
final int userInterface.UIManager.PEN_COLOR_INDEX = 1 static
Definition at line 31 of file UIManager.java.
Referenced by userInterface.TopMenu.initialize().
final int userInterface.UIManager.PEN_SIZE_INDEX = 2 static
Definition at line 32 of file UIManager.java.
Referenced by userInterface.TopMenu.initialize().
ObjectProperty<String> userInterface.UIManager.penColor package
Definition at line 49 of file UIManager.java.
ObjectProperty<Double> userInterface.UIManager.penSize private
Definition at line 50 of file UIManager.java.
final String userInterface.UIManager.TAB_NAME = "SLogo #" static private
Definition at line 36 of file UIManager.java.
final int userInterface.UIManager.TURTLE_IMAGE_INDEX = 3 static
Definition at line 33 of file UIManager.java.
Referenced by userInterface.TopMenu.initialize(), and turtle.Turtle.setUpBindings().
ObjectProperty<Image> userInterface.UIManager.turtleImage private
Definition at line 51 of file UIManager.java.
final int userInterface.UIManager.UI_HEIGHT = 750 static
Definition at line 29 of file UIManager.java.
final int userInterface.UIManager.UI_WIDTH = 1000 static
UIManager can hold multiple tabs of SLogo and holds the menu bar that controls features such as the background color, turtle image, etc.
Definition at line 28 of file UIManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/UIManager.java