slogo_team07: userInterface.UI Class Reference
userInterface.UI Class Reference
Public Member Functions
UI (List< ObjectProperty > bindings)
Pane getUI ()
GraphicsContext getGraphics ()
Canvas getCanvas ()
StackPane getPane ()
Static Public Attributes
static final int PANEL_WIDTH = 200
static final int PANEL_HEIGHT = 500
Package Attributes
BorderPane myCenterView
Private Member Functions
void initialize (List< ObjectProperty > bindings)
void setUpController ()
void setUpCommandField ()
Button makeRunButton ()
void setUpPane ()
void runCommand ()
Private Attributes
WorldController myController
BorderPane myView
HBox myCommandField
TextArea myInput
boolean firstClick
RightPanel myRightPanel
LeftPanel myLeftPanel
Canvas myCanvas
GraphicsContext myGC
StackPane canvasPane
StringProperty inputText
List< ObjectProperty > myBindings
ObjectProperty< ResourceBundle > myLanguage
ObjectProperty< String > myCanvasColor
Static Private Attributes
static final String PLAY_BUTTON = "resources/images/PlayButton.jpg"
static final int INPUT_WIDTH = 450
static final int INPUT_HEIGHT = 300
Detailed Description
Definition at line 27 of file UI.java.
Constructor & Destructor Documentation
userInterface.UI.UI (List< ObjectProperty > bindings)
Definition at line 55 of file UI.java.
References userInterface.UI.initialize().
Member Function Documentation
Canvas userInterface.UI.getCanvas ()
Definition at line 172 of file UI.java.
References userInterface.UI.myCanvas.
Referenced by worldController.WorldController.WorldController().
GraphicsContext userInterface.UI.getGraphics ()
Definition at line 168 of file UI.java.
References userInterface.UI.myGC.
Referenced by worldController.WorldController.WorldController().
StackPane userInterface.UI.getPane ()
Definition at line 176 of file UI.java.
References userInterface.UI.canvasPane.
Referenced by worldController.WorldController.WorldController().
Pane userInterface.UI.getUI ()
Returns
BorderPane myView
Definition at line 62 of file UI.java.
References userInterface.UI.myView.
Referenced by userInterface.UIManager.addTab().
void userInterface.UI.initialize (List< ObjectProperty > bindings) private
initializes the UI by creating border panes and setting up necessary components such as the command field
Parameters
List<ObjectProperty> bindings
Definition at line 72 of file UI.java.
References userInterface.UIManager.CANVAS_INDEX, userInterface.LeftPanel.getInstance(), userInterface.RightPanel.getInstance(), userInterface.LeftPanel.getPanel(), userInterface.RightPanel.getPanel(), userInterface.UIManager.LANGUAGE_INDEX, userInterface.UI.setUpCommandField(), userInterface.UI.setUpController(), and userInterface.UI.setUpPane().
Referenced by userInterface.UI.UI().
Button userInterface.UI.makeRunButton () private
creates run button
Returns
Button play
Definition at line 139 of file UI.java.
References userInterface.UI.runCommand().
Referenced by userInterface.UI.setUpCommandField().
void userInterface.UI.runCommand () private
called to run whatever command(s) are in the command field
Definition at line 163 of file UI.java.
References worldController.WorldController.update().
Referenced by userInterface.UI.makeRunButton().
void userInterface.UI.setUpCommandField () private
sets up the command field which will be cleared the first time it is clicked and whenever it is played
binding between inputText and myInput allows the user to double click a saved or previous command and have it appear in the command box
Definition at line 115 of file UI.java.
References userInterface.UI.makeRunButton().
Referenced by userInterface.UI.initialize().
void userInterface.UI.setUpController () private
sets up the WorldController
Definition at line 98 of file UI.java.
Referenced by userInterface.UI.initialize().
void userInterface.UI.setUpPane () private
sets up the canvas pane with the canvas and graphics context
Definition at line 151 of file UI.java.
Referenced by userInterface.UI.initialize().
Member Data Documentation
StackPane userInterface.UI.canvasPane private
Definition at line 49 of file UI.java.
Referenced by userInterface.UI.getPane().
boolean userInterface.UI.firstClick private
Definition at line 44 of file UI.java.
final int userInterface.UI.INPUT_HEIGHT = 300 static private
Definition at line 38 of file UI.java.
final int userInterface.UI.INPUT_WIDTH = 450 static private
Definition at line 37 of file UI.java.
StringProperty userInterface.UI.inputText private
Definition at line 50 of file UI.java.
List<ObjectProperty> userInterface.UI.myBindings private
Definition at line 51 of file UI.java.
Canvas userInterface.UI.myCanvas private
Definition at line 47 of file UI.java.
Referenced by userInterface.UI.getCanvas().
ObjectProperty<String> userInterface.UI.myCanvasColor private
Definition at line 53 of file UI.java.
BorderPane userInterface.UI.myCenterView package
Definition at line 41 of file UI.java.
HBox userInterface.UI.myCommandField private
Definition at line 42 of file UI.java.
WorldController userInterface.UI.myController private
Definition at line 40 of file UI.java.
GraphicsContext userInterface.UI.myGC private
Definition at line 48 of file UI.java.
Referenced by userInterface.UI.getGraphics().
TextArea userInterface.UI.myInput private
Definition at line 43 of file UI.java.
ObjectProperty<ResourceBundle> userInterface.UI.myLanguage private
Definition at line 52 of file UI.java.
LeftPanel userInterface.UI.myLeftPanel private
Definition at line 46 of file UI.java.
RightPanel userInterface.UI.myRightPanel private
Definition at line 45 of file UI.java.
BorderPane userInterface.UI.myView private
Definition at line 41 of file UI.java.
Referenced by userInterface.UI.getUI().
final int userInterface.UI.PANEL_HEIGHT = 500 static
Definition at line 35 of file UI.java.
Referenced by userInterface.LeftPanel.initialize(), and userInterface.RightPanel.initialize().
final int userInterface.UI.PANEL_WIDTH = 200 static
UI represents the user interface of a single instance of SLogo. Multiple instances can be added by creating a new tab in UIManager
Definition at line 34 of file UI.java.
Referenced by userInterface.LeftPanel.initialize(), and userInterface.RightPanel.initialize().
final String userInterface.UI.PLAY_BUTTON = "resources/images/PlayButton.jpg" static private
Definition at line 36 of file UI.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/UI.java