slogo_team07: userInterface.Topbar Class Reference
userInterface.Topbar Class Reference
Public Member Functions
Topbar ()
HBox getTopbar ()
Protected Attributes
ComboBox< String > languageChoices
ColorPicker myColorChoices
Private Member Functions
void initialize ()
Hyperlink createHelpLink ()
void displayWebpage ()
HBox createColorChoices ()
ComboBox< String > createLanguageOptions ()
Private Attributes
HBox myHBox
Hyperlink myLink
Static Private Attributes
static final String[] LANGUAGES
static final int SPACING = 40
Detailed Description
Definition at line 24 of file Topbar.java.
Constructor & Destructor Documentation
userInterface.Topbar.Topbar ()
Definition at line 36 of file Topbar.java.
References userInterface.Topbar.initialize().
Member Function Documentation
HBox userInterface.Topbar.createColorChoices () private
Definition at line 72 of file Topbar.java.
Referenced by userInterface.Topbar.initialize().
Hyperlink userInterface.Topbar.createHelpLink () private
Definition at line 51 of file Topbar.java.
References userInterface.Topbar.displayWebpage(), and userInterface.Topbar.myLink.
Referenced by userInterface.Topbar.initialize().
ComboBox<String> userInterface.Topbar.createLanguageOptions () private
Definition at line 80 of file Topbar.java.
References userInterface.Topbar.languageChoices.
Referenced by userInterface.Topbar.initialize().
void userInterface.Topbar.displayWebpage () private
Definition at line 57 of file Topbar.java.
Referenced by userInterface.Topbar.createHelpLink().
HBox userInterface.Topbar.getTopbar ()
Definition at line 40 of file Topbar.java.
References userInterface.Topbar.myHBox.
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.Topbar.initialize () private
Definition at line 44 of file Topbar.java.
References userInterface.Topbar.createColorChoices(), userInterface.Topbar.createHelpLink(), and userInterface.Topbar.createLanguageOptions().
Referenced by userInterface.Topbar.Topbar().
Member Data Documentation
ComboBox<String> userInterface.Topbar.languageChoices protected
Definition at line 32 of file Topbar.java.
Referenced by userInterface.Topbar.createLanguageOptions(), and userInterface.UserInterface.setUpResponses().
final String [] userInterface.Topbar.LANGUAGES static private
Initial value:
= { "Chinese", "English", "French", "German",
                                               "Italian", "Japanese", "Korean", "Portuguese",
                                               "Russian", "Spanish" }
Definition at line 26 of file Topbar.java.
ColorPicker userInterface.Topbar.myColorChoices protected
Definition at line 34 of file Topbar.java.
Referenced by userInterface.UserInterface.setUpResponses().
HBox userInterface.Topbar.myHBox private
Definition at line 31 of file Topbar.java.
Referenced by userInterface.Topbar.getTopbar().
Hyperlink userInterface.Topbar.myLink private
Definition at line 33 of file Topbar.java.
Referenced by userInterface.Topbar.createHelpLink().
final int userInterface.Topbar.SPACING = 40 static private
Definition at line 29 of file Topbar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/Topbar.java