slogo_team07: userInterface.UserInterface Class Reference
userInterface.UserInterface Class Reference
Public Member Functions
UserInterface () throws IOException
Scene getScene ()
void setUpController () throws IOException
void refresh (String s)
GraphicsContext getGraphics ()
Timeline getTimeline ()
Canvas getCanvas ()
StackPane getPane ()
Sidebar getSidebar ()
Static Public Attributes
static final int BOX_WIDTH = 180
Private Member Functions
void setUpResponses ()
void setupPane ()
TextArea makeCommandWindow ()
void makeFunctionButtons ()
void makeSwitchTurtle ()
void addTurtle ()
void changeTurtle ()
void saveCommand (String s)
void runCommand (String data)
void makeCreateTurtle ()
void makeSaveCommand ()
void makeTimeline ()
Button makeUIButton (String s, EventHandler< MouseEvent > e)
void makeRunButton ()
Private Attributes
WorldController myController
Scene myScene
BorderPane myRoot
Sidebar mySidebar
Topbar myTopbar
ResourceBundle myMenuNames
TextArea myCommandWindow
Timeline myAnimation
Canvas myCanvas
GraphicsContext myGC
StackPane canvasPane
Button commandSaverButton
Static Private Attributes
static final int myWidth = 900
static final int myHeight = 750
static final String DEFAULT_RESOURCE_PACKAGE = "resources/languages/"
static final String DEFAULT_IMAGE_PACKAGE = "resources/images/"
Detailed Description
Author
Brandon Choi, James Mosca
Definition at line 31 of file UserInterface.java.
Constructor & Destructor Documentation
userInterface.UserInterface.UserInterface () throws IOException
Definition at line 52 of file UserInterface.java.
References userInterface.Sidebar.getSidebar(), userInterface.Topbar.getTopbar(), userInterface.UserInterface.makeCommandWindow(), userInterface.UserInterface.makeCreateTurtle(), userInterface.UserInterface.makeFunctionButtons(), userInterface.UserInterface.makeSaveCommand(), userInterface.UserInterface.makeTimeline(), userInterface.UserInterface.setupPane(), and userInterface.UserInterface.setUpResponses().
Member Function Documentation
void userInterface.UserInterface.addTurtle () private
Definition at line 149 of file UserInterface.java.
void userInterface.UserInterface.changeTurtle () private
Definition at line 155 of file UserInterface.java.
Referenced by userInterface.UserInterface.makeSwitchTurtle().
Canvas userInterface.UserInterface.getCanvas ()
Definition at line 215 of file UserInterface.java.
References userInterface.UserInterface.myCanvas.
Referenced by worldController.WorldController.WorldController().
GraphicsContext userInterface.UserInterface.getGraphics ()
Definition at line 207 of file UserInterface.java.
References userInterface.UserInterface.myGC.
Referenced by worldController.WorldController.WorldController().
StackPane userInterface.UserInterface.getPane ()
Definition at line 219 of file UserInterface.java.
References userInterface.UserInterface.canvasPane.
Referenced by worldController.WorldController.WorldController().
Scene userInterface.UserInterface.getScene ()
Definition at line 77 of file UserInterface.java.
References userInterface.UserInterface.myScene.
Referenced by Main.start().
Sidebar userInterface.UserInterface.getSidebar ()
Definition at line 223 of file UserInterface.java.
References userInterface.UserInterface.mySidebar.
Referenced by worldController.WorldController.update().
Timeline userInterface.UserInterface.getTimeline ()
Definition at line 211 of file UserInterface.java.
References userInterface.UserInterface.myAnimation.
Referenced by worldController.WorldController.WorldController().
TextArea userInterface.UserInterface.makeCommandWindow () private
Definition at line 133 of file UserInterface.java.
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.UserInterface.makeCreateTurtle () private
Definition at line 167 of file UserInterface.java.
References userInterface.Sidebar.add().
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.UserInterface.makeFunctionButtons () private
Definition at line 139 of file UserInterface.java.
References userInterface.UserInterface.makeRunButton(), and userInterface.UserInterface.makeSwitchTurtle().
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.UserInterface.makeRunButton () private
Definition at line 193 of file UserInterface.java.
References userInterface.Sidebar.add(), userInterface.UserInterface.makeUIButton(), and userInterface.UserInterface.runCommand().
Referenced by userInterface.UserInterface.makeFunctionButtons().
void userInterface.UserInterface.makeSaveCommand () private
Definition at line 174 of file UserInterface.java.
References userInterface.Sidebar.add().
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.UserInterface.makeSwitchTurtle () private
Definition at line 144 of file UserInterface.java.
References userInterface.Sidebar.add(), userInterface.UserInterface.changeTurtle(), and userInterface.UserInterface.makeUIButton().
Referenced by userInterface.UserInterface.makeFunctionButtons().
void userInterface.UserInterface.makeTimeline () private
Definition at line 180 of file UserInterface.java.
Referenced by userInterface.UserInterface.UserInterface().
Button userInterface.UserInterface.makeUIButton (String s, EventHandler< MouseEvent > e) private
Definition at line 186 of file UserInterface.java.
Referenced by userInterface.UserInterface.makeRunButton(), and userInterface.UserInterface.makeSwitchTurtle().
void userInterface.UserInterface.refresh (String s)
Definition at line 203 of file UserInterface.java.
void userInterface.UserInterface.runCommand (String data) private
Definition at line 163 of file UserInterface.java.
References worldController.WorldController.update().
Referenced by userInterface.UserInterface.makeRunButton(), and userInterface.UserInterface.setUpResponses().
void userInterface.UserInterface.saveCommand (String s) private
Definition at line 159 of file UserInterface.java.
void userInterface.UserInterface.setUpController () throws IOException
Definition at line 129 of file UserInterface.java.
Referenced by Main.start().
void userInterface.UserInterface.setupPane () private
Definition at line 119 of file UserInterface.java.
Referenced by userInterface.UserInterface.UserInterface().
void userInterface.UserInterface.setUpResponses () private
Definition at line 81 of file UserInterface.java.
References userInterface.Sidebar.addItem(), userInterface.Sidebar.boxes, userInterface.CommandSaver.close(), userInterface.CommandSaver.commandWindow, userInterface.Topbar.languageChoices, userInterface.Topbar.myColorChoices, userInterface.UserInterface.runCommand(), userInterface.CommandSaver.saveButton, userInterface.CommandSaver.saveCommand(), and userInterface.Sidebar.SAVED_INDEX.
Referenced by userInterface.UserInterface.UserInterface().
Member Data Documentation
final int userInterface.UserInterface.BOX_WIDTH = 180 static
Definition at line 33 of file UserInterface.java.
Referenced by userInterface.Sidebar.setUpComboBox(), and userInterface.Sidebar.setUpResults().
StackPane userInterface.UserInterface.canvasPane private
Definition at line 49 of file UserInterface.java.
Referenced by userInterface.UserInterface.getPane().
Button userInterface.UserInterface.commandSaverButton private
Definition at line 50 of file UserInterface.java.
final String userInterface.UserInterface.DEFAULT_IMAGE_PACKAGE = "resources/images/" static private
Definition at line 37 of file UserInterface.java.
final String userInterface.UserInterface.DEFAULT_RESOURCE_PACKAGE = "resources/languages/" static private
Definition at line 36 of file UserInterface.java.
Timeline userInterface.UserInterface.myAnimation private
Definition at line 46 of file UserInterface.java.
Referenced by userInterface.UserInterface.getTimeline().
Canvas userInterface.UserInterface.myCanvas private
Definition at line 47 of file UserInterface.java.
Referenced by userInterface.UserInterface.getCanvas().
TextArea userInterface.UserInterface.myCommandWindow private
Definition at line 45 of file UserInterface.java.
WorldController userInterface.UserInterface.myController private
Definition at line 39 of file UserInterface.java.
GraphicsContext userInterface.UserInterface.myGC private
Definition at line 48 of file UserInterface.java.
Referenced by userInterface.UserInterface.getGraphics().
final int userInterface.UserInterface.myHeight = 750 static private
Definition at line 35 of file UserInterface.java.
ResourceBundle userInterface.UserInterface.myMenuNames private
Definition at line 44 of file UserInterface.java.
BorderPane userInterface.UserInterface.myRoot private
Definition at line 41 of file UserInterface.java.
Scene userInterface.UserInterface.myScene private
Definition at line 40 of file UserInterface.java.
Referenced by userInterface.UserInterface.getScene().
Sidebar userInterface.UserInterface.mySidebar private
Definition at line 42 of file UserInterface.java.
Referenced by userInterface.UserInterface.getSidebar().
Topbar userInterface.UserInterface.myTopbar private
Definition at line 43 of file UserInterface.java.
final int userInterface.UserInterface.myWidth = 900 static private
Definition at line 34 of file UserInterface.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/UserInterface.java