slogo_team07: userInterface.ErrorMessage Class Reference
userInterface.ErrorMessage Class Reference
Public Member Functions
ErrorMessage (String error)
Private Member Functions
void initialize (String s)
Text createErrorText (String s)
Button createOKButton ()
void show ()
Private Attributes
Stage myStage
VBox myMessageContent
Text errorText
Button okButton
Static Private Attributes
static final int MESSAGE_WIDTH = 250
static final int MESSAGE_HEIGHT = 150
static final int SPACING = 10
static final String BUTTON_TEXT = "OK"
Detailed Description
Definition at line 16 of file ErrorMessage.java.
Constructor & Destructor Documentation
userInterface.ErrorMessage.ErrorMessage (String error)
Definition at line 32 of file ErrorMessage.java.
References userInterface.ErrorMessage.initialize(), and userInterface.ErrorMessage.show().
Member Function Documentation
Text userInterface.ErrorMessage.createErrorText (String s) private
creates the appropriate error text based on the string given
Parameters
String s
Returns
Text errorText
Definition at line 55 of file ErrorMessage.java.
References userInterface.ErrorMessage.errorText.
Referenced by userInterface.ErrorMessage.initialize().
Button userInterface.ErrorMessage.createOKButton () private
creates the OK button that will close the error message
Returns
Button okButton
Definition at line 66 of file ErrorMessage.java.
References userInterface.ErrorMessage.okButton.
Referenced by userInterface.ErrorMessage.initialize().
void userInterface.ErrorMessage.initialize (String s) private
initializes and creates the ErrorMessage object
Parameters
String s
Definition at line 42 of file ErrorMessage.java.
References userInterface.ErrorMessage.createErrorText(), and userInterface.ErrorMessage.createOKButton().
Referenced by userInterface.ErrorMessage.ErrorMessage().
void userInterface.ErrorMessage.show () private
displays the error message as a popup on a new stage
Definition at line 75 of file ErrorMessage.java.
Referenced by userInterface.ErrorMessage.ErrorMessage().
Member Data Documentation
final String userInterface.ErrorMessage.BUTTON_TEXT = "OK" static private
Definition at line 26 of file ErrorMessage.java.
Text userInterface.ErrorMessage.errorText private
Definition at line 29 of file ErrorMessage.java.
Referenced by userInterface.ErrorMessage.createErrorText().
final int userInterface.ErrorMessage.MESSAGE_HEIGHT = 150 static private
Definition at line 24 of file ErrorMessage.java.
final int userInterface.ErrorMessage.MESSAGE_WIDTH = 250 static private
ErrorMessage will pop up whenever there is an issue in the program such as if a user inputs an invalid command
Definition at line 23 of file ErrorMessage.java.
VBox userInterface.ErrorMessage.myMessageContent private
Definition at line 28 of file ErrorMessage.java.
Stage userInterface.ErrorMessage.myStage private
Definition at line 27 of file ErrorMessage.java.
Button userInterface.ErrorMessage.okButton private
Definition at line 30 of file ErrorMessage.java.
Referenced by userInterface.ErrorMessage.createOKButton().
final int userInterface.ErrorMessage.SPACING = 10 static private
Definition at line 25 of file ErrorMessage.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/ErrorMessage.java