slogo_team07: parser.Parser Class Reference
parser.Parser Class Reference
Public Member Functions
Parser (String language, ObservableMap< String, Double > var, ObservableMap< String, String > functions2, List< ObjectProperty > bind, ObservableList< Color > color)
int initializeCommands (String input)
Command parse (String valueFromPrevCommand)
void setLanguage (String language)
void updateVariable (String variable, double variableValue)
void resetRepcount ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
List< String > generateCommandInput (String valueFromPrevCommand, Node current)
Node getNodeForCommand ()
Node getNodeBeforeToReplace ()
Node makeTree (Scanner input)
Private Attributes
CommandFactory myCommandFactory
ResourceBundle myResources
Node myTree
Node myListTree
String myInput
int numCommands
ObservableMap< String, Double > variables
ObservableMap< String, String > functions
List< ObjectProperty > bindings
ObservableList< Color > colors
Static Private Attributes
static final String LIST = "list"
Detailed Description
Definition at line 24 of file Parser.java.
Constructor & Destructor Documentation
parser.Parser.Parser (String language, ObservableMap< String, Double > var, ObservableMap< String, String > functions2, List< ObjectProperty > bind, ObservableList< Color > color)
Definition at line 37 of file Parser.java.
Referenced by parser.Parser.main().
Member Function Documentation
List<String> parser.Parser.generateCommandInput (String valueFromPrevCommand, Node current) private
Returns a list containing the elements (value of node of most nested command and its children) needed to pass into myCommandFactory to generate a command.
Parameters
String valueFromPrevCommand
Node current
Returns
List<String>
Definition at line 108 of file Parser.java.
References parser.Node.getChild1(), parser.Node.getChild2(), parser.Node.getValue(), and parser.Node.numChildren().
Referenced by parser.Parser.parse().
Node parser.Parser.getNodeBeforeToReplace () private
Traverses the tree and retrieves the node that is the parent of the most nested command in order to replace that with the value of the most nested command executed.
Returns
Node
Definition at line 168 of file Parser.java.
References parser.Node.getChild1(), parser.Node.getChild2(), parser.Node.getValue(), parser.Node.hasChildren(), parser.Node.isLeaf(), and parser.Parser.myTree.
Referenced by parser.Parser.parse().
Node parser.Parser.getNodeForCommand () private
Traverses the tree and returns the deepest (most nested) command.
Returns
Node
Definition at line 141 of file Parser.java.
References parser.Node.getChild1(), parser.Node.getChild2(), parser.Node.hasChildren(), parser.Node.isLeaf(), and parser.Parser.myTree.
Referenced by parser.Parser.parse().
int parser.Parser.initializeCommands (String input)
Initializes the tree based on the user input
Parameters
input
Returns
int numCommands
Definition at line 56 of file Parser.java.
References parser.Parser.makeTree(), and parser.Parser.numCommands.
Referenced by world.World.listen(), and parser.Parser.main().
static void parser.Parser.main (String[] args) static
Definition at line 259 of file Parser.java.
References parser.Parser.initializeCommands(), parser.Parser.parse(), and parser.Parser.Parser().
Node parser.Parser.makeTree (Scanner input) private
Creates tree out of Nodes using regex. Constants and variables are leaf children of commands. If a list is detected, creates anothr tree for the contents of the list.
Parameters
input
Returns
Node
Definition at line 212 of file Parser.java.
References command.CommandFactory.getNumParameters().
Referenced by parser.Parser.initializeCommands(), and parser.Parser.parse().
Command parser.Parser.parse (String valueFromPrevCommand)
Replaces value from the previously executed command in the tree and retrieves the next command to be executed.
Parameters
valueFromPrevCommand
Returns
Command
Definition at line 75 of file Parser.java.
References command.CommandFactory.createCommand(), parser.Parser.generateCommandInput(), parser.Parser.getNodeBeforeToReplace(), parser.Parser.getNodeForCommand(), parser.Node.insertChild(), parser.Parser.makeTree(), and parser.Parser.myListTree.
Referenced by world.World.listen(), and parser.Parser.main().
void parser.Parser.resetRepcount ()
Definition at line 289 of file Parser.java.
References command.CommandFactory.resetRepcount().
Referenced by world.World.listen().
void parser.Parser.setLanguage (String language)
Ability to change language of input
Parameters
language
Definition at line 255 of file Parser.java.
References command.CommandFactory.setLanguage().
Referenced by world.World.setLanguage().
void parser.Parser.updateVariable (String variable, double variableValue)
Calls method in myCommandFactory to update the variablecount in a loop.
Parameters
variable
variableValue
Definition at line 285 of file Parser.java.
References command.CommandFactory.updateVariable().
Referenced by world.World.listen().
Member Data Documentation
List<ObjectProperty> parser.Parser.bindings private
Definition at line 34 of file Parser.java.
ObservableList<Color> parser.Parser.colors private
Definition at line 35 of file Parser.java.
ObservableMap<String, String> parser.Parser.functions private
Definition at line 33 of file Parser.java.
final String parser.Parser.LIST = "list" static private
Definition at line 31 of file Parser.java.
CommandFactory parser.Parser.myCommandFactory private
Definition at line 25 of file Parser.java.
String parser.Parser.myInput private
Definition at line 29 of file Parser.java.
Node parser.Parser.myListTree private
Definition at line 28 of file Parser.java.
Referenced by parser.Parser.parse().
ResourceBundle parser.Parser.myResources private
Definition at line 26 of file Parser.java.
Node parser.Parser.myTree private
Definition at line 27 of file Parser.java.
Referenced by parser.Parser.getNodeBeforeToReplace(), and parser.Parser.getNodeForCommand().
int parser.Parser.numCommands private
Definition at line 30 of file Parser.java.
Referenced by parser.Parser.initializeCommands().
ObservableMap<String, Double> parser.Parser.variables private
Definition at line 32 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/parser/Parser.java