slogo_team07: userInterface.RightPanel Class Reference
userInterface.RightPanel Class Reference
Public Member Functions
RightPanel ()
VBox getPanel ()
void initialize (ObservableList< String > r, ObservableList< String > p, ObservableList< String > s, StringProperty t)
Static Public Member Functions
static synchronized RightPanel getInstance ()
Private Member Functions
VBox makeListView (ListView view, ObservableList list, String name)
Private Attributes
VBox myRightPanel
ObservableList< String > results
ObservableList< String > previousCommands
ObservableList< String > savedCommands
ListView< String > resultsView
ListView< String > previousCommandView
ListView< String > savedCommandView
StringProperty inputText
Static Private Attributes
static final int DOUBLE_CLICK = 2
static final String RESULTS_LABEL = "Results"
static final String SAVED_COMMANDS_LABEL = "Saved Commands"
static final String PREVIOUS_COMMANDS_LABEL = "Previous Commands"
static final int RIGHT_PANEL_SPACING = 10
static RightPanel instance
Detailed Description
Definition at line 14 of file RightPanel.java.
Constructor & Destructor Documentation
userInterface.RightPanel.RightPanel ()
Definition at line 38 of file RightPanel.java.
Referenced by userInterface.RightPanel.getInstance().
Member Function Documentation
static synchronized RightPanel userInterface.RightPanel.getInstance () static
implements Singleton model
Returns
RightPanel instance
Definition at line 46 of file RightPanel.java.
References userInterface.RightPanel.instance, and userInterface.RightPanel.RightPanel().
Referenced by userInterface.UI.initialize(), and worldController.WorldController.WorldController().
VBox userInterface.RightPanel.getPanel ()
for accessing the panel from the UI
Returns
VBox myRightPanel
Definition at line 60 of file RightPanel.java.
References userInterface.RightPanel.myRightPanel.
Referenced by userInterface.UI.initialize().
void userInterface.RightPanel.initialize (ObservableList< String > r, ObservableList< String > p, ObservableList< String > s, StringProperty t)
initializes the components and binds necessary objects together
Parameters
ObservableList<String> r
ObservableList<String> p
ObservableList<String> s
String Property t
Definition at line 72 of file RightPanel.java.
References userInterface.RightPanel.DOUBLE_CLICK, userInterface.RightPanel.makeListView(), userInterface.UI.PANEL_HEIGHT, and userInterface.UI.PANEL_WIDTH.
VBox userInterface.RightPanel.makeListView (ListView view, ObservableList list, String name) private
general method used to create a ListView with any view, list, and name
Parameters
ListView view
ObservableList list
String name
Returns
Definition at line 110 of file RightPanel.java.
Referenced by userInterface.RightPanel.initialize().
Member Data Documentation
final int userInterface.RightPanel.DOUBLE_CLICK = 2 static private
RightPanel is the right hand portion of the UI. It holds the results, previous commands, and saved commands. The previous and saved commands can be double clicked to run again if desired.
Definition at line 22 of file RightPanel.java.
Referenced by userInterface.RightPanel.initialize().
StringProperty userInterface.RightPanel.inputText private
Definition at line 36 of file RightPanel.java.
RightPanel userInterface.RightPanel.instance static private
Definition at line 28 of file RightPanel.java.
Referenced by userInterface.RightPanel.getInstance().
VBox userInterface.RightPanel.myRightPanel private
Definition at line 29 of file RightPanel.java.
Referenced by userInterface.RightPanel.getPanel().
final String userInterface.RightPanel.PREVIOUS_COMMANDS_LABEL = "Previous Commands" static private
Definition at line 25 of file RightPanel.java.
ObservableList<String> userInterface.RightPanel.previousCommands private
Definition at line 31 of file RightPanel.java.
ListView<String> userInterface.RightPanel.previousCommandView private
Definition at line 34 of file RightPanel.java.
ObservableList<String> userInterface.RightPanel.results private
Definition at line 30 of file RightPanel.java.
final String userInterface.RightPanel.RESULTS_LABEL = "Results" static private
Definition at line 23 of file RightPanel.java.
ListView<String> userInterface.RightPanel.resultsView private
Definition at line 33 of file RightPanel.java.
final int userInterface.RightPanel.RIGHT_PANEL_SPACING = 10 static private
Definition at line 26 of file RightPanel.java.
final String userInterface.RightPanel.SAVED_COMMANDS_LABEL = "Saved Commands" static private
Definition at line 24 of file RightPanel.java.
ObservableList<String> userInterface.RightPanel.savedCommands private
Definition at line 32 of file RightPanel.java.
ListView<String> userInterface.RightPanel.savedCommandView private
Definition at line 35 of file RightPanel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team07/repository/src/userInterface/RightPanel.java